baseURL = ''
languageCode = 'en-us'
title = 'Pet Food Depot Laguna'
theme = 'LucentLink-Hugo'
[params]
  description     = ""
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]